plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

sourceSets {
    main {
        java {
            srcDir 'src/main/java/'
        }
        resources {
            srcDir 'Images/'
        }
    }
}

jar {
    manifest {
        attributes(
            'Main-Class': 'DCourt.DCourtFrame',
        )
    }
}

